apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chainmesh-redis-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: chainmesh-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
