apiVersion: v1
kind: Service
metadata:
  name: chainmesh-redis-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: chainmesh-redis
spec:
  type: {{ .Values.service.type }}
  selector:
    app: chainmesh-redis
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: redis
