ALTER TABLE tenants
    ADD COLUMN IF NOT EXISTS plan TEXT NOT NULL DEFAULT 'free';

ALTER TABLE tenants
    ADD COLUMN IF NOT EXISTS quota_rps INTEGER NOT NULL DEFAULT 0;

ALTER TABLE tenants
    ADD COLUMN IF NOT EXISTS quota_daily INTEGER NOT NULL DEFAULT 0;