apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainmesh-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: chainmesh-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chainmesh-gateway
  template:
    metadata:
      labels:
        app: chainmesh-gateway
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      securityContext: {{ toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          envFrom: {{ toYaml .Values.envFrom | nindent 12 }}
          env:
            - name: DATABASE_URL
              value: "host=chainmesh-postgresql-svc port=5432 user=$(DATABASE_USER) password=$(DATABASE_PASSWORD) dbname=$(POSTGRES_DB) sslmode=disable"
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources: {{ toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
      volumes:
        - name: tmp
          emptyDir: {}